const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Category = require('./models/Category');
const Prompt = require('./models/Prompt');
const Admin = require('./models/Admin');

// 100+ Prompts across all categories
const generatePrompts = (categoryMap) => [
  // Study & Learning (10 prompts)
  { title: 'Feynman Technique Explainer', content: 'Explain [TOPIC] as if I\'m a complete beginner. Use simple analogies, real-world examples, and avoid jargon. Break it down into fundamental concepts, then build up. After explaining, give me 3 questions to test my understanding.', description: 'Use the Feynman technique to deeply understand any topic', category: categoryMap['Study & Learning'], tags: ['feynman', 'learning', 'explanation', 'study'], difficulty: 'beginner', aiModel: 'Any', isFeatured: true },
  { title: 'Active Recall Flashcard Generator', content: 'Create 15 high-quality flashcard pairs (Q&A) for [SUBJECT/TOPIC]. Format: Q: [question]\nA: [answer]. Make questions specific and answers concise. Include definitions, concepts, and application questions.', description: 'Generate effective flashcards for any subject', category: categoryMap['Study & Learning'], tags: ['flashcards', 'memorization', 'active recall'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Research Paper Summarizer', content: 'Summarize the research paper on [TOPIC] with: 1) Core Question, 2) Methodology, 3) Key Findings (3-5), 4) Significance, 5) Limitations, 6) Key Terms (5 definitions)', description: 'Break down complex academic papers into digestible summaries', category: categoryMap['Study & Learning'], tags: ['research', 'academic', 'summary'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Study Schedule Creator', content: 'Create a 4-week study plan for [SUBJECT] with daily 2-hour sessions. Break into: 30min warmup, 90min focused study, 30min review. Include breaks and weekly tests.', description: 'Generate personalized study schedules', category: categoryMap['Study & Learning'], tags: ['planning', 'schedule', 'study'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Essay Outline Generator', content: 'Create a detailed essay outline for the topic "[TOPIC]" with thesis statement, 3-5 main points with subpoints, counterargument, and conclusion strategy.', description: 'Structure essays with comprehensive outlines', category: categoryMap['Study & Learning'], tags: ['writing', 'essay', 'outline'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Quiz Question Creator', content: 'Generate 20 multiple-choice questions for [SUBJECT/CHAPTER] with 4 options each. Include answer key with explanations. Vary difficulty levels.', description: 'Create comprehensive quiz questions', category: categoryMap['Study & Learning'], tags: ['quiz', 'testing', 'assessment'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Concept Mapping Guide', content: 'Create a concept map for [TOPIC] showing relationships between [NUMBER] key concepts. Use hierarchical structure with connecting lines and descriptive labels.', description: 'Visualize topic relationships', category: categoryMap['Study & Learning'], tags: ['visual', 'concepts', 'mapping'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Exam Preparation Guide', content: 'Create a comprehensive exam prep guide for [EXAM NAME] including: key topics, practice problems, common mistakes, time management tips, and last-minute review checklist.', description: 'Prepare strategically for exams', category: categoryMap['Study & Learning'], tags: ['exam', 'preparation', 'tips'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Literature Analysis Framework', content: 'Analyze [BOOK/TEXT] using: theme identification, character analysis, symbolism, literary devices, historical context, and personal interpretation.', description: 'Analyze literature systematically', category: categoryMap['Study & Learning'], tags: ['literature', 'analysis', 'books'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Math Problem Solver', content: 'Solve this [MATH PROBLEM] step-by-step, showing all work. Explain the concept behind each step. Provide alternative solution methods if applicable.', description: 'Solve math problems with detailed explanations', category: categoryMap['Study & Learning'], tags: ['math', 'problem-solving', 'step-by-step'], difficulty: 'beginner', aiModel: 'Any' },

  // Instagram Trending (10 prompts)
  { title: 'Viral Caption Generator', content: 'Create a viral Instagram caption for [TOPIC/PRODUCT]. Include: hook, story (2-3 sentences), value, CTA, 3-5 relevant emojis, 10-15 hashtags. Target: [AUDIENCE]. Tone: [PROFESSIONAL/CASUAL/INSPIRATIONAL]', description: 'Create viral-worthy Instagram captions', category: categoryMap['Instagram Trending'], tags: ['instagram', 'viral', 'caption'], difficulty: 'beginner', aiModel: 'Any', isFeatured: true },
  { title: 'Content Calendar Creator', content: 'Create a 30-day Instagram content calendar for [NICHE]. Include 6 posts/week with content type (carousel, reel, story), caption ideas, hashtag suggestions, posting time, and engagement tips.', description: 'Plan Instagram content systematically', category: categoryMap['Instagram Trending'], tags: ['planning', 'content', 'calendar'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Reel Script Generator', content: 'Write a 30-60 second Instagram Reel script for [TOPIC]. Include: opening hook, 3-4 key points, visuals/effects suggestions, trending sound recommendations, CTA, and hashtags.', description: 'Create engaging Reel scripts', category: categoryMap['Instagram Trending'], tags: ['reel', 'script', 'video'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Hashtag Strategy Builder', content: 'Create a hashtag strategy for [NICHE/CONTENT TYPE]. Provide: 10 high-volume hashtags, 10 medium-volume hashtags, 10 niche-specific hashtags, usage rules, and rotation strategy.', description: 'Optimize hashtag strategy', category: categoryMap['Instagram Trending'], tags: ['hashtags', 'strategy', 'growth'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Carousel Post Creator', content: 'Design a 5-slide carousel post about [TOPIC]. Each slide: main idea, supporting graphic description, text, and CTA. Include caption, hashtags, and engagement prompts.', description: 'Create carousel posts', category: categoryMap['Instagram Trending'], tags: ['carousel', 'post', 'design'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Story Series Planner', content: 'Plan a 10-story Instagram Story series for [CAMPAIGN/TOPIC]. Include: story flow, text/stickers, CTAs, timing, and conversion tracking strategy.', description: 'Plan Instagram Story series', category: categoryMap['Instagram Trending'], tags: ['stories', 'series', 'engagement'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Influencer Collaboration Brief', content: 'Create an influencer collaboration brief for [CAMPAIGN]. Include: campaign goals, target audience, deliverables, timeline, budget, brand guidelines, and success metrics.', description: 'Plan influencer partnerships', category: categoryMap['Instagram Trending'], tags: ['influencer', 'collaboration', 'campaign'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Instagram Analytics Interpreter', content: 'Analyze these Instagram insights [INSERT METRICS] and provide: key takeaways, performance analysis, audience demographics interpretation, and 5 actionable recommendations.', description: 'Interpret Instagram analytics', category: categoryMap['Instagram Trending'], tags: ['analytics', 'data', 'insights'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Trendjacking Ideas Generator', content: 'Generate 5 trendjacking ideas for [CURRENT TREND]. For each: how to adapt your brand/content, captions, hashtags, timing, and engagement strategy.', description: 'Capitalize on trending topics', category: categoryMap['Instagram Trending'], tags: ['trends', 'viral', 'timely'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Bio Optimization Guide', content: 'Optimize Instagram bio for [NICHE/BRAND]. Create: compelling headline (150 chars), bio description with keywords, link strategy, emoji usage, and CTA suggestions.', description: 'Create compelling bios', category: categoryMap['Instagram Trending'], tags: ['bio', 'profile', 'optimization'], difficulty: 'beginner', aiModel: 'Any' },

  // Software Development (10 prompts)
  { title: 'Code Refactoring Guide', content: 'Refactor this [LANGUAGE] code [CODE]: identify improvements, apply SOLID principles, enhance readability, optimize performance, add comments. Show before/after with explanations.', description: 'Improve code quality', category: categoryMap['Software Development'], tags: ['code', 'refactoring', 'optimization'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'API Design Architect', content: 'Design a REST API for [PROJECT]. Include: endpoints, request/response schemas, authentication, error handling, versioning, rate limiting, and documentation structure.', description: 'Design robust APIs', category: categoryMap['Software Development'], tags: ['api', 'design', 'rest'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Database Schema Designer', content: 'Design a database schema for [APPLICATION/PROJECT]. Include: tables, relationships, constraints, indexing strategy, normalization approach, and sample queries.', description: 'Design efficient databases', category: categoryMap['Software Development'], tags: ['database', 'schema', 'sql'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Bug Fix Assistant', content: 'Help me fix this bug: [ERROR/ISSUE]. Provide: root cause analysis, step-by-step fix, code changes, testing strategy, and prevention tips for similar bugs.', description: 'Debug code efficiently', category: categoryMap['Software Development'], tags: ['debugging', 'bug', 'fix'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Algorithm Explainer', content: 'Explain the [ALGORITHM NAME] algorithm: how it works, time/space complexity, when to use it, code example in [LANGUAGE], visual representation, and real-world applications.', description: 'Understand algorithms deeply', category: categoryMap['Software Development'], tags: ['algorithm', 'complexity', 'data-structures'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'System Design Interviewer', content: 'Design [SYSTEM] (e.g., URL shortener, chat app). Cover: requirements, architecture, data flow, database design, scalability, caching, load balancing, and trade-offs.', description: 'Master system design', category: categoryMap['Software Development'], tags: ['system-design', 'architecture', 'interview'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Testing Strategy Generator', content: 'Create a comprehensive testing strategy for [PROJECT/FEATURE] including: unit tests, integration tests, e2e tests, test cases, coverage goals, and automation approach.', description: 'Plan quality assurance', category: categoryMap['Software Development'], tags: ['testing', 'qa', 'automation'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Documentation Writer', content: 'Write technical documentation for [PROJECT/COMPONENT]. Include: overview, installation, usage examples, API reference, configuration options, troubleshooting, and FAQs.', description: 'Create clear documentation', category: categoryMap['Software Development'], tags: ['documentation', 'technical-writing'], difficulty: 'intermediate', apiModel: 'Any' },
  { title: 'Git Workflow Guide', content: 'Explain Git workflow for [TEAM SIZE/PROJECT TYPE]. Include: branch strategy, commit conventions, PR process, merge strategy, conflict resolution, and best practices.', description: 'Master version control', category: categoryMap['Software Development'], tags: ['git', 'version-control', 'workflow'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Performance Optimization Tips', content: 'Optimize [APPLICATION/CODE] for performance. Analyze: bottlenecks, caching strategies, database optimization, frontend optimization, monitoring, and benchmarking approach.', description: 'Improve app performance', category: categoryMap['Software Development'], tags: ['performance', 'optimization', 'speed'], difficulty: 'advanced', aiModel: 'Any' },

  // Physical Fitness (10 prompts)
  { title: 'Personalized Workout Plan', content: 'Create a 12-week [GOAL] workout plan for someone [CURRENT FITNESS LEVEL]. Include: 4-5 sessions/week, exercises, sets/reps, rest days, progression, and warm-up/cool-down routines.', description: 'Design custom fitness programs', category: categoryMap['Physical Fitness'], tags: ['workout', 'fitness', 'exercise'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'Nutrition & Meal Plan', content: 'Create a [DURATION] meal plan for [GOAL] with [DIETARY RESTRICTION]. Include: daily calories, macros, 3 meals + 2 snacks, recipes, shopping list, and prep tips.', description: 'Plan nutrition programs', category: categoryMap['Physical Fitness'], tags: ['nutrition', 'diet', 'meal-plan'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Home Workout Generator', content: 'Create a 30-minute no-equipment home workout for [GOAL] with [AVAILABLE SPACE]. Include: warm-up, 8-10 exercises, sets/reps, rest periods, cool-down, and modifications.', description: 'Design home workouts', category: categoryMap['Physical Fitness'], tags: ['home-workout', 'no-equipment', 'bodyweight'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Injury Recovery Plan', content: 'Design a recovery plan for [INJURY] with [CURRENT STAGE]. Include: exercises, progression timeline, physical therapy tips, pain management, and return-to-activity strategy.', description: 'Guide injury rehabilitation', category: categoryMap['Physical Fitness'], tags: ['injury', 'recovery', 'rehabilitation'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'HIIT Workout Creator', content: 'Create a 20-minute HIIT workout for [GOAL]. Structure: 5min warm-up, 40/20 sec work/rest intervals with 8-10 exercises, 2 rounds, 3min cool-down. Include modifications.', description: 'Design high-intensity workouts', category: categoryMap['Physical Fitness'], tags: ['hiit', 'cardio', 'quick-workout'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Strength Training Program', content: 'Create a [DURATION] strength training program. Include: rep ranges, exercises, progressive overload strategy, recovery recommendations, and supplementation advice.', description: 'Build muscle systematically', category: categoryMap['Physical Fitness'], tags: ['strength', 'muscle', 'weights'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Flexibility & Mobility Routine', content: 'Design a [DURATION] stretching/mobility routine for [TARGET AREA] with [FLEXIBILITY LEVEL]. Include: hold times, reps, benefits of each stretch, and progression options.', description: 'Improve flexibility', category: categoryMap['Physical Fitness'], tags: ['stretching', 'mobility', 'flexibility'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Fitness Goal Tracker', content: 'Create a fitness tracking system for [GOAL]. Include: weekly check-ins, progress photos schedule, measurements to track, benchmark exercises, and milestone celebrations.', description: 'Track fitness progress', category: categoryMap['Physical Fitness'], tags: ['tracking', 'progress', 'goals'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Sport-Specific Training', content: 'Design a sport-specific training program for [SPORT]. Include: skill drills, fitness components, weekly structure, periodization, and competitive readiness timeline.', description: 'Train for specific sports', category: categoryMap['Physical Fitness'], tags: ['sports', 'training', 'athletic'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Workout Motivation Guide', content: 'Create a motivation strategy for [PERSON/SITUATION]. Include: goal-setting framework, tracking methods, accountability buddy tips, reward system, and habit-building strategies.', description: 'Build fitness consistency', category: categoryMap['Physical Fitness'], tags: ['motivation', 'habits', 'consistency'], difficulty: 'beginner', aiModel: 'Any' },

  // Health & Wellness (10 prompts)
  { title: 'Wellness Plan Creator', content: 'Design a comprehensive wellness plan covering: physical health, mental health, sleep, stress management, nutrition, exercise, social connections, and self-care for [PERSON].', description: 'Create holistic wellness plans', category: categoryMap['Health & Wellness'], tags: ['wellness', 'health', 'holistic'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'Sleep Optimization Guide', content: 'Create a sleep improvement plan for [SLEEP ISSUE] including: sleep hygiene tips, bedroom environment optimization, schedule recommendations, and bedtime routine design.', description: 'Improve sleep quality', category: categoryMap['Health & Wellness'], tags: ['sleep', 'insomnia', 'rest'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Stress Management Toolkit', content: 'Build a stress management toolkit for [STRESSOR] with: 5 immediate relief techniques, daily practices, weekly rituals, boundary-setting strategies, and professional resources.', description: 'Manage stress effectively', category: categoryMap['Health & Wellness'], tags: ['stress', 'mental-health', 'anxiety'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Mental Health Journal Prompts', content: 'Create 30 therapeutic journal prompts for [MENTAL HEALTH GOAL]. Include: self-reflection questions, gratitude exercises, emotional processing prompts, and goal-setting questions.', description: 'Guide journaling practice', category: categoryMap['Health & Wellness'], tags: ['journaling', 'therapy', 'mental-health'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Meditation Guide Creator', content: 'Write a guided meditation script for [PURPOSE] (5-10 minutes). Include: calming introduction, body scan, visualization, affirmations, and gentle closing.', description: 'Create meditation scripts', category: categoryMap['Health & Wellness'], tags: ['meditation', 'mindfulness', 'relaxation'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Nutrition for Wellness', content: 'Design a nutrition plan for [HEALTH GOAL] considering [DIETARY PREFERENCE]. Include: anti-inflammatory foods, superfoods, hydration strategy, and meal timing.', description: 'Optimize nutrition for health', category: categoryMap['Health & Wellness'], tags: ['nutrition', 'diet', 'health'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Detox & Cleanse Guide', content: 'Create a safe [DURATION] detox plan including: foods to eat/avoid, hydration protocol, supplements, exercise recommendations, and expected timelines/side effects.', description: 'Guide healthy detoxification', category: categoryMap['Health & Wellness'], tags: ['detox', 'cleanse', 'wellness'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Immune System Booster', content: 'Design an immune system optimization plan covering: immunity-boosting foods, supplements, lifestyle habits, stress reduction, sleep improvement, and seasonal strategies.', description: 'Strengthen immune health', category: categoryMap['Health & Wellness'], tags: ['immunity', 'health', 'prevention'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Energy & Fatigue Management', content: 'Create an energy management plan for [FATIGUE TYPE]. Include: energy audit, daily schedule optimization, nutrition for energy, exercise timing, and recovery strategies.', description: 'Manage energy levels', category: categoryMap['Health & Wellness'], tags: ['energy', 'fatigue', 'vitality'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Holistic Health Assessment', content: 'Conduct a holistic health assessment for [PERSON]. Evaluate: physical, mental, emotional, social, and spiritual health. Provide: strengths, areas for improvement, and action plan.', description: 'Assess overall health', category: categoryMap['Health & Wellness'], tags: ['assessment', 'holistic', 'evaluation'], difficulty: 'advanced', aiModel: 'Any' },

  // Business & Marketing (10 prompts)
  { title: 'Marketing Strategy Blueprint', content: 'Create a comprehensive marketing strategy for [BUSINESS/PRODUCT]. Include: market analysis, target audience, positioning, channels, budget allocation, KPIs, and 12-month timeline.', description: 'Develop marketing strategies', category: categoryMap['Business & Marketing'], tags: ['marketing', 'strategy', 'business'], difficulty: 'advanced', aiModel: 'Any', isFeatured: true },
  { title: 'Email Marketing Campaign', content: 'Design an email campaign for [GOAL] including: 5-email sequence, subject lines, body copy, CTAs, send timing, A/B test strategy, and success metrics.', description: 'Create email campaigns', category: categoryMap['Business & Marketing'], tags: ['email', 'marketing', 'campaign'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Social Media Strategy', content: 'Develop a [DURATION] social media strategy for [PLATFORM/BUSINESS]. Include: content pillars, posting schedule, engagement tactics, community management, and growth goals.', description: 'Plan social media growth', category: categoryMap['Business & Marketing'], tags: ['social-media', 'strategy', 'growth'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Sales Funnel Optimizer', content: 'Create a high-converting sales funnel for [PRODUCT]. Include: awareness, consideration, decision stages with tactics, copywriting, nurture sequences, and conversion rate optimization.', description: 'Design sales funnels', category: categoryMap['Business & Marketing'], tags: ['sales', 'funnel', 'conversion'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Content Marketing Plan', content: 'Create a 90-day content marketing plan for [BUSINESS]. Include: content themes, editorial calendar, 20 content ideas, distribution strategy, and engagement goals.', description: 'Plan content marketing', category: categoryMap['Business & Marketing'], tags: ['content', 'marketing', 'strategy'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Brand Positioning Strategy', content: 'Develop brand positioning for [COMPANY/PRODUCT]. Include: brand promise, unique value proposition, target audience, brand personality, messaging pillars, and visual identity guidelines.', description: 'Establish brand identity', category: categoryMap['Business & Marketing'], tags: ['branding', 'positioning', 'identity'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Customer Retention Program', content: 'Design a customer retention program for [BUSINESS]. Include: loyalty rewards, exclusive benefits, personalization strategies, communication plan, and retention metrics.', description: 'Build customer loyalty', category: categoryMap['Business & Marketing'], tags: ['retention', 'loyalty', 'customers'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Market Research Guide', content: 'Create a market research plan for [PRODUCT/MARKET]. Include: research methods, competitor analysis framework, customer surveys, data collection, and insights synthesis.', description: 'Conduct market research', category: categoryMap['Business & Marketing'], tags: ['research', 'market', 'competitors'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Business Plan Template', content: 'Create a detailed business plan for [STARTUP/IDEA]. Include: executive summary, market analysis, business model, financial projections, team, and growth strategy.', description: 'Develop business plans', category: categoryMap['Business & Marketing'], tags: ['business-plan', 'startup', 'strategy'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Growth Hacking Ideas', content: 'Generate 10 growth hacking ideas for [BUSINESS/PRODUCT]. For each: tactic, implementation steps, expected impact, resource needs, and success metrics.', description: 'Identify growth opportunities', category: categoryMap['Business & Marketing'], tags: ['growth', 'hacking', 'innovation'], difficulty: 'advanced', aiModel: 'Any' },

  // Creative Writing (10 prompts)
  { title: 'Story Plot Generator', content: 'Create a [GENRE] story plot including: premise, protagonist, antagonist, main conflict, plot points, climax, resolution, and 3-act structure. Target word count: [LENGTH].', description: 'Develop compelling story plots', category: categoryMap['Creative Writing'], tags: ['writing', 'story', 'plot'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'Character Development Guide', content: 'Develop a complex character for [STORY/GENRE]. Include: background, personality, motivations, conflicts, arc, dialogue style, physical description, and relationships with other characters.', description: 'Create compelling characters', category: categoryMap['Creative Writing'], tags: ['character', 'development', 'writing'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Dialogue Writing Masterclass', content: 'Improve dialogue for [SCENE/GENRE]. Provide: techniques for natural conversation, character voice differentiation, subtext, pacing, tension, and 3 dialogue examples.', description: 'Write authentic dialogue', category: categoryMap['Creative Writing'], tags: ['dialogue', 'conversation', 'writing'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Poetry Generator', content: 'Create [NUMBER] [POETRY STYLE] poems on [TOPIC]. Include: varied lengths, imagery, metaphors, rhythm, and emotional depth. Suitable for: [PURPOSE].', description: 'Generate poetry', category: categoryMap['Creative Writing'], tags: ['poetry', 'creative', 'writing'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Scriptwriting Framework', content: 'Write a [DURATION] [GENRE] script for [PROJECT]. Include: scene descriptions, dialogue, action, pacing, visual storytelling, and technical requirements.', description: 'Write scripts and screenplays', category: categoryMap['Creative Writing'], tags: ['script', 'screenwriting', 'film'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'World Building Guide', content: 'Build a fictional world for [STORY]. Include: geography, climate, cultures, government, magic/technology systems, history, and how these affect the plot.', description: 'Create fictional universes', category: categoryMap['Creative Writing'], tags: ['world-building', 'fiction', 'fantasy'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Flash Fiction Creator', content: 'Write a [LENGTH]-word flash fiction piece on [PROMPT]. Include: compelling hook, vivid imagery, character development, twist ending, and emotional resonance.', description: 'Write short fiction', category: categoryMap['Creative Writing'], tags: ['flash-fiction', 'short-story'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Writing Prompt Generator', content: 'Create 20 unique writing prompts for [GENRE/TYPE]. Each should include: scenario, character setup, conflict hint, and emotional tone to inspire creativity.', description: 'Generate writing inspiration', category: categoryMap['Creative Writing'], tags: ['prompts', 'inspiration', 'writing'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Editing & Revision Guide', content: 'Edit this [GENRE] writing: [TEXT]. Provide: grammar corrections, clarity improvements, style suggestions, pacing feedback, and a revised version.', description: 'Refine written work', category: categoryMap['Creative Writing'], tags: ['editing', 'revision', 'writing'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Book Outline Creator', content: 'Create a detailed outline for a [GENRE] book: [TITLE/CONCEPT]. Include: chapter breakdown (20-30 chapters), key plot points, character arcs, and narrative structure.', description: 'Plan novels and books', category: categoryMap['Creative Writing'], tags: ['book', 'outline', 'planning'], difficulty: 'advanced', aiModel: 'Any' },

  // Productivity (10 prompts)
  { title: 'Goal Setting Framework', content: 'Create a [TIMEFRAME] goal-setting plan for [GOAL]. Use SMART framework: define specific goals, measurable metrics, achievable milestones, relevant context, and timeline.', description: 'Set and achieve goals', category: categoryMap['Productivity'], tags: ['goals', 'planning', 'productivity'], difficulty: 'beginner', aiModel: 'Any', isFeatured: true },
  { title: 'Time Management System', content: 'Design a time management system for [CONTEXT]. Include: task categorization, priority matrix, scheduling approach, time blocking, distraction management, and accountability.', description: 'Master time management', category: categoryMap['Productivity'], tags: ['time', 'management', 'organization'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Daily Routine Optimization', content: 'Create an optimized daily routine for [PERSON/ROLE]. Include: wake time, exercise, work blocks, breaks, meals, evening routine, and sleep schedule based on [GOAL].', description: 'Design productive routines', category: categoryMap['Productivity'], tags: ['routine', 'daily', 'habits'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Project Management Plan', content: 'Create a project plan for [PROJECT]. Include: scope, timeline, milestones, tasks, dependencies, resource allocation, risk management, and success metrics.', description: 'Plan and manage projects', category: categoryMap['Productivity'], tags: ['project', 'management', 'planning'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Procrastination Buster', content: 'Create a procrastination override plan for [TASK]. Identify: underlying causes, implementation intentions, environmental design, rewards, accountability, and progress tracking.', description: 'Overcome procrastination', category: categoryMap['Productivity'], tags: ['procrastination', 'motivation', 'action'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Habit Formation Guide', content: 'Design a habit formation plan for [HABIT]. Include: habit stacking, environment design, identity alignment, tracking system, streak motivation, and troubleshooting strategies.', description: 'Build lasting habits', category: categoryMap['Productivity'], tags: ['habits', 'behavior-change', 'discipline'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Meeting Efficiency Guide', content: 'Create a meeting protocol for [ORGANIZATION]. Include: meeting types, agenda templates, duration, participants, decision-making process, and follow-up procedures.', description: 'Streamline meetings', category: categoryMap['Productivity'], tags: ['meetings', 'efficiency', 'communication'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Knowledge Management System', content: 'Design a personal knowledge management system for [PURPOSE]. Include: note-taking method, organization structure, review schedule, search system, and integration with daily work.', description: 'Organize knowledge', category: categoryMap['Productivity'], tags: ['knowledge', 'organization', 'systems'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Decision-Making Framework', content: 'Create a decision-making framework for [DECISION TYPE]. Include: criteria definition, evaluation matrix, stakeholder input, risk assessment, and decision documentation.', description: 'Make better decisions', category: categoryMap['Productivity'], tags: ['decision', 'framework', 'analysis'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Delegation Strategy', content: 'Develop a delegation strategy for [TEAM/PROJECT]. Include: task analysis, skill matching, authority levels, feedback systems, and performance monitoring.', description: 'Master delegation', category: categoryMap['Productivity'], tags: ['delegation', 'leadership', 'management'], difficulty: 'advanced', aiModel: 'Any' },

  // Language Learning (10 prompts)
  { title: 'Language Learning Plan', content: 'Create a [DURATION] learning plan for [LANGUAGE]. Include: daily study schedule (minutes), skills (listening, speaking, reading, writing), resources, and progress milestones.', description: 'Plan language learning', category: categoryMap['Language Learning'], tags: ['language', 'learning', 'study'], difficulty: 'beginner', aiModel: 'Any', isFeatured: true },
  { title: 'Vocabulary Builder', content: 'Create a 30-day vocabulary program for [LANGUAGE] focused on [TOPIC]. Provide: 10 words daily, definitions, usage examples, pronunciation, and memory techniques.', description: 'Expand vocabulary', category: categoryMap['Language Learning'], tags: ['vocabulary', 'language', 'words'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Grammar Explanation', content: 'Explain [GRAMMAR RULE] in [LANGUAGE]. Include: rule definition, examples (5+), common mistakes, exceptions, and 3 practice exercises with answers.', description: 'Master grammar', category: categoryMap['Language Learning'], tags: ['grammar', 'language', 'rules'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Conversation Practice Guide', content: 'Create a conversation practice guide for [LANGUAGE] on [TOPIC]. Include: phrases, dialogue examples, pronunciation tips, natural expressions, and cultural context.', description: 'Improve speaking skills', category: categoryMap['Language Learning'], tags: ['conversation', 'speaking', 'practice'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Translation Assistance', content: 'Translate [TEXT] from [SOURCE LANGUAGE] to [TARGET LANGUAGE]. Provide: direct translation, cultural adaptations, idioms, and explanations of translation choices.', description: 'Translate accurately', category: categoryMap['Language Learning'], tags: ['translation', 'language', 'bilingual'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Language Immersion Plan', content: 'Design an immersion strategy for [LANGUAGE]. Include: media consumption (movies, podcasts), exchange programs, practice groups, travel planning, and tracking progress.', description: 'Immerse in language', category: categoryMap['Language Learning'], tags: ['immersion', 'practice', 'fluency'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Accent Reduction Guide', content: 'Create an accent reduction plan for [LANGUAGE]. Include: phoneme identification, articulation exercises, listening drills, shadowing technique, and practice schedule.', description: 'Improve pronunciation', category: categoryMap['Language Learning'], tags: ['pronunciation', 'accent', 'speaking'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Language Exam Prep', content: 'Create a study plan for [LANGUAGE EXAM]. Include: test structure, key topics, practice materials, timing strategies, and 5 full-length practice tests with answers.', description: 'Prepare for language tests', category: categoryMap['Language Learning'], tags: ['exam', 'test-prep', 'language'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Cultural Context Guide', content: 'Explain cultural context for [LANGUAGE]. Include: customs, idioms, historical background, social norms, and how they affect language use.', description: 'Understand language culture', category: categoryMap['Language Learning'], tags: ['culture', 'context', 'language'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Slang & Expressions Guide', content: 'Create a guide to [LANGUAGE] slang and colloquial expressions. Include: 20 common phrases, regional variations, when to use, and cultural appropriateness.', description: 'Learn natural language', category: categoryMap['Language Learning'], tags: ['slang', 'colloquial', 'expressions'], difficulty: 'intermediate', aiModel: 'Any' },

  // Art & Design (10 prompts)
  { title: 'Design Brief Creator', content: 'Create a design brief for [PROJECT]. Include: project overview, objectives, target audience, style preferences, constraints, deliverables, timeline, and budget.', description: 'Create design briefs', category: categoryMap['Art & Design'], tags: ['design', 'brief', 'project'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'Color Palette Generator', content: 'Create a [THEME] color palette for [PROJECT]. Provide: 5-7 colors (hex codes), usage guidelines, psychology, contrast ratios, and mood implications.', description: 'Design color schemes', category: categoryMap['Art & Design'], tags: ['color', 'design', 'palette'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Logo Design Guide', content: 'Guide logo design for [BRAND]. Include: design principles, concept ideas (3+), font recommendations, color options, variations (horizontal, vertical, favicon), and usage guidelines.', description: 'Design logos', category: categoryMap['Art & Design'], tags: ['logo', 'branding', 'design'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Typography Guide', content: 'Create a typography guide for [PROJECT]. Include: font pairs, sizes, weights, line heights, letter spacing, hierarchy, and usage rules for web/print.', description: 'Master typography', category: categoryMap['Art & Design'], tags: ['typography', 'fonts', 'design'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'User Experience (UX) Plan', content: 'Design UX for [DIGITAL PRODUCT]. Include: user personas, user journey, wireframes (descriptions), information architecture, interaction patterns, and usability principles.', description: 'Design user experiences', category: categoryMap['Art & Design'], tags: ['ux', 'design', 'user-research'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Brand Style Guide', content: 'Create a comprehensive brand style guide. Include: logo guidelines, color palette, typography, imagery style, tone of voice, spacing, and dos/don\'ts.', description: 'Develop brand guidelines', category: categoryMap['Art & Design'], tags: ['branding', 'style-guide', 'design'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Illustration Style Guide', content: 'Develop an illustration style guide for [BRAND/PROJECT]. Define: art style, line weight, color usage, composition approach, and 5 example illustrations.', description: 'Define illustration styles', category: categoryMap['Art & Design'], tags: ['illustration', 'art', 'style'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Layout & Composition', content: 'Explain composition techniques for [DESIGN TYPE]. Cover: rule of thirds, golden ratio, balance, emphasis, white space, and 3 layout examples.', description: 'Master design composition', category: categoryMap['Art & Design'], tags: ['composition', 'layout', 'design'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Design Feedback Framework', content: 'Create a framework for giving/receiving design feedback. Include: evaluation criteria, constructive criticism techniques, design principles, and feedback templates.', description: 'Critique designs effectively', category: categoryMap['Art & Design'], tags: ['feedback', 'critique', 'design'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Motion Design Guide', content: 'Create a motion design guide for [PROJECT]. Include: animation principles, easing, timing, transitions, effects, and when to use motion.', description: 'Design animations', category: categoryMap['Art & Design'], tags: ['animation', 'motion', 'design'], difficulty: 'advanced', aiModel: 'Any' },

  // Finance & Investing (10 prompts)
  { title: 'Financial Planning Guide', content: 'Create a financial plan for [PERSON/GOAL]. Include: income analysis, expense breakdown, debt strategy, savings goals, investment recommendations, and 5-year projection.', description: 'Plan finances', category: categoryMap['Finance & Investing'], tags: ['finance', 'planning', 'money'], difficulty: 'advanced', aiModel: 'Any', isFeatured: true },
  { title: 'Investment Strategy Builder', content: 'Develop an investment strategy for [INVESTOR PROFILE]. Include: risk assessment, asset allocation, diversification, portfolio options, and expected returns.', description: 'Build investment portfolios', category: categoryMap['Finance & Investing'], tags: ['investment', 'portfolio', 'stocks'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Budget Creation Masterclass', content: 'Create a budget for [TIMEFRAME] with [INCOME]. Include: categories, allocations, tracking methods, adjustments, and savings strategy using [BUDGETING METHOD].', description: 'Design budgets', category: categoryMap['Finance & Investing'], tags: ['budget', 'money', 'planning'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Stock Analysis Guide', content: 'Analyze stock [TICKER]. Include: company overview, financial metrics, valuation analysis, competitive position, risks, and investment recommendation.', description: 'Analyze stocks', category: categoryMap['Finance & Investing'], tags: ['stocks', 'analysis', 'investing'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Passive Income Strategy', content: 'Create a passive income plan for [GOAL/TIMELINE]. Include: income sources (5+), setup requirements, maintenance, expected returns, and tax implications.', description: 'Generate passive income', category: categoryMap['Finance & Investing'], tags: ['passive-income', 'money', 'investing'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Debt Elimination Plan', content: 'Design a debt payoff strategy for [DEBT TYPE/AMOUNT]. Include: payoff methods (snowball/avalanche), timeline, motivation, and prevention strategies.', description: 'Eliminate debt', category: categoryMap['Finance & Investing'], tags: ['debt', 'payoff', 'money'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Retirement Planning Guide', content: 'Create a retirement plan for [PERSON]. Include: retirement goal, investment strategy, contribution schedule, withdrawal plan, and lifestyle planning.', description: 'Plan for retirement', category: categoryMap['Finance & Investing'], tags: ['retirement', 'planning', 'investing'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Real Estate Investment Guide', content: 'Develop a real estate investment strategy. Include: property analysis, financing options, ROI calculations, tax benefits, and risk management.', description: 'Invest in real estate', category: categoryMap['Finance & Investing'], tags: ['real-estate', 'investment', 'property'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Cryptocurrency Guide', content: 'Explain cryptocurrency for [LEVEL]. Cover: blockchain technology, major coins, wallets, exchanges, security, risks, and investment strategy.', description: 'Understand crypto', category: categoryMap['Finance & Investing'], tags: ['cryptocurrency', 'blockchain', 'investing'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Tax Optimization Strategies', content: 'Create tax optimization strategies for [SITUATION]. Include: deductions, credits, timing strategies, account types, and estimated tax savings.', description: 'Minimize taxes', category: categoryMap['Finance & Investing'], tags: ['tax', 'optimization', 'finance'], difficulty: 'advanced', aiModel: 'Any' },

  // Cooking & Recipes (10 prompts)
  { title: 'Meal Plan Creator', content: 'Create a [DURATION] meal plan for [DIET TYPE] with [BUDGET]. Include: 3 meals + 1 snack daily, recipes, shopping list, prep tips, and nutritional info.', description: 'Plan meals systematically', category: categoryMap['Cooking & Recipes'], tags: ['meal-plan', 'recipes', 'cooking'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'Recipe Developer', content: 'Create a recipe for [DISH] based on [CUISINE/DIETARY PREFERENCE]. Include: ingredients (with amounts), instructions, cooking time, servings, tips, and nutritional information.', description: 'Develop recipes', category: categoryMap['Cooking & Recipes'], tags: ['recipe', 'cooking', 'food'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Cooking Technique Guide', content: 'Explain [COOKING TECHNIQUE]. Include: definition, step-by-step instructions, tools needed, common mistakes, tips for mastery, and 3 dishes using this technique.', description: 'Master cooking techniques', category: categoryMap['Cooking & Recipes'], tags: ['technique', 'cooking', 'skills'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Ingredient Substitution Guide', content: 'Create substitution suggestions for [INGREDIENT]. Provide: 5 alternatives with ratios, flavor implications, and recipes where each works best.', description: 'Find ingredient replacements', category: categoryMap['Cooking & Recipes'], tags: ['substitution', 'ingredients', 'cooking'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Menu Planning Service', content: 'Design a [DURATION] menu for [EVENT/OCCASION]. Include: appetizers, mains, sides, desserts, wines pairings, timeline, and prep strategy.', description: 'Plan menus for events', category: categoryMap['Cooking & Recipes'], tags: ['menu', 'entertaining', 'planning'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Dietary Adaptation Guide', content: 'Adapt [RECIPE] for [DIETARY NEED]. Explain: ingredient swaps, technique modifications, and how to maintain flavors and texture.', description: 'Adapt recipes for diets', category: categoryMap['Cooking & Recipes'], tags: ['diet', 'vegan', 'allergy-free'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Food Preservation Guide', content: 'Create a guide to preserving [FOOD TYPE]. Include: methods (canning, freezing, fermenting), step-by-step instructions, storage, and shelf life.', description: 'Preserve food safely', category: categoryMap['Cooking & Recipes'], tags: ['preservation', 'canning', 'storage'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Cuisine Mastery Course', content: 'Teach [CUISINE] cooking fundamentals. Include: key techniques, essential ingredients, cultural context, 5 signature recipes, and tasting notes.', description: 'Learn cuisine styles', category: categoryMap['Cooking & Recipes'], tags: ['cuisine', 'cooking', 'cultural'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Kitchen Equipment Guide', content: 'Guide on using [KITCHEN EQUIPMENT]. Include: how it works, best uses, maintenance, safety tips, and 5 recipes featuring this tool.', description: 'Master kitchen tools', category: categoryMap['Cooking & Recipes'], tags: ['equipment', 'tools', 'kitchen'], difficulty: 'beginner', aiModel: 'Any' },
  { title: 'Pantry Stocking Guide', content: 'Create an essentials list for [CUISINE/DIET]. Include: staple foods, spices, condiments, storage tips, and how to use each item.', description: 'Stock your pantry', category: categoryMap['Cooking & Recipes'], tags: ['pantry', 'staples', 'cooking'], difficulty: 'beginner', aiModel: 'Any' },

  // Career & Resume (10 prompts)
  { title: 'Resume Optimizer', content: 'Optimize this resume for [JOB TITLE]. Provide: formatting improvements, keyword optimization, content suggestions, ATS-friendly changes, and achievement rewriting.', description: 'Perfect your resume', category: categoryMap['Career & Resume'], tags: ['resume', 'career', 'job-search'], difficulty: 'intermediate', aiModel: 'Any', isFeatured: true },
  { title: 'Cover Letter Creator', content: 'Write a cover letter for [POSITION] at [COMPANY]. Include: compelling opening, relevant skills/experience, company enthusiasm, and strong closing.', description: 'Write cover letters', category: categoryMap['Career & Resume'], tags: ['cover-letter', 'job-search', 'writing'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Interview Preparation Guide', content: 'Create an interview prep guide for [POSITION/COMPANY]. Include: common questions, STAR method examples, company research, questions to ask, and follow-up strategy.', description: 'Ace job interviews', category: categoryMap['Career & Resume'], tags: ['interview', 'preparation', 'job-search'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Career Development Plan', content: 'Create a [TIMEFRAME] career development plan for [CURRENT ROLE/GOAL]. Include: skills to develop, experience needed, timeline, and milestones.', description: 'Plan career growth', category: categoryMap['Career & Resume'], tags: ['career', 'development', 'growth'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Salary Negotiation Guide', content: 'Create a salary negotiation strategy for [ROLE/COMPANY]. Include: market research, negotiation tactics, walk-away point, and benefits discussion.', description: 'Negotiate compensation', category: categoryMap['Career & Resume'], tags: ['salary', 'negotiation', 'career'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'LinkedIn Profile Optimizer', content: 'Optimize LinkedIn for [CAREER GOAL]. Improve: headline, summary, experience descriptions, skills, recommendations, and photo.', description: 'Boost LinkedIn presence', category: categoryMap['Career & Resume'], tags: ['linkedin', 'networking', 'career'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Personal Brand Builder', content: 'Develop a personal brand for [PROFESSIONAL]. Include: unique value proposition, messaging pillars, visual identity, and online presence strategy.', description: 'Create personal brands', category: categoryMap['Career & Resume'], tags: ['branding', 'career', 'personal-brand'], difficulty: 'advanced', aiModel: 'Any' },
  { title: 'Job Search Strategy', content: 'Create a [TIMEFRAME] job search plan for [DESIRED ROLE]. Include: target companies, application strategy, networking plan, and timeline.', description: 'Conduct effective job searches', category: categoryMap['Career & Resume'], tags: ['job-search', 'career', 'strategy'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Networking Guide', content: 'Create a networking strategy for [INDUSTRY/GOAL]. Include: networking types, conversation starters, relationship building, and follow-up system.', description: 'Build professional networks', category: categoryMap['Career & Resume'], tags: ['networking', 'career', 'relationships'], difficulty: 'intermediate', aiModel: 'Any' },
  { title: 'Skill Gap Analysis', content: 'Analyze skills for [DESIRED ROLE]. Include: required skills, your current skills, gaps identified, learning resources, and development timeline.', description: 'Identify skill gaps', category: categoryMap['Career & Resume'], tags: ['skills', 'analysis', 'development'], difficulty: 'intermediate', aiModel: 'Any' }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Create categories
    const categories = [
      { name: 'Instagram Trending', icon: '📸', color: '#e1306c', description: 'Trending prompts and ideas for Instagram content creation', order: 1 },
      { name: 'Study & Learning', icon: '📚', color: '#3b82f6', description: 'Prompts for students, research, and academic learning', order: 2 },
      { name: 'Software Development', icon: '💻', color: '#8b5cf6', description: 'Code generation, debugging, architecture, and tech prompts', order: 3 },
      { name: 'Physical Fitness', icon: '💪', color: '#f59e0b', description: 'Workout plans, exercise routines, and fitness guidance', order: 4 },
      { name: 'Health & Wellness', icon: '🏥', color: '#10b981', description: 'Health advice, nutrition, mental wellness prompts', order: 5 },
      { name: 'Business & Marketing', icon: '📈', color: '#ef4444', description: 'Marketing copy, business strategy, and entrepreneurship', order: 6 },
      { name: 'Creative Writing', icon: '✍️', color: '#ec4899', description: 'Stories, poetry, scripts, and creative content', order: 7 },
      { name: 'Productivity', icon: '⚡', color: '#06b6d4', description: 'Task management, time optimization, goal setting', order: 8 },
      { name: 'Language Learning', icon: '🌍', color: '#f97316', description: 'Language practice, translation, grammar prompts', order: 9 },
      { name: 'Art & Design', icon: '🎨', color: '#a855f7', description: 'Image generation, design feedback, creative direction', order: 10 },
      { name: 'Finance & Investing', icon: '💰', color: '#84cc16', description: 'Financial planning, investment analysis, budgeting', order: 11 },
      { name: 'Cooking & Recipes', icon: '🍳', color: '#fb923c', description: 'Recipe creation, meal planning, cooking guidance', order: 12 },
      { name: 'Career & Resume', icon: '🎯', color: '#64748b', description: 'Resume writing, interview prep, career guidance', order: 13 }
    ];

    await Category.deleteMany({});
    const savedCategories = await Category.create(categories);
    const categoryMap = {};
    savedCategories.forEach(cat => categoryMap[cat.name] = cat._id);
    console.log('✅ Created 13 categories');

    // Generate and save prompts
    await Prompt.deleteMany({});
    const prompts = generatePrompts(categoryMap);
    await Prompt.create(prompts);
    console.log(`✅ Created ${prompts.length} prompts`);

    // Create admin account for admin@promptvault.com
    await Admin.deleteMany({});
    await Admin.create({
      name: 'Admin User',
      email: 'admin@promptvault.com',
      password: 'Admin@123456',
      role: 'superadmin'
    });
    console.log('✅ Created admin@promptvault.com');

    // Also create the default admin
    await Admin.create({
      name: 'Super Admin',
      email: 'admin@promptcraftery.com',
      password: 'Admin@123456',
      role: 'superadmin'
    });
    console.log('✅ Created admin@promptcraftery.com');

    console.log('\n🎉 Database restoration complete!');
    console.log(`Total prompts: ${prompts.length}`);
    console.log('Admins created:');
    console.log('- admin@promptvault.com / Admin@123456');
    console.log('- admin@promptcraftery.com / Admin@123456');

    await mongoose.disconnect();
  } catch (err) {
    console.error('Error seeding database:', err);
    process.exit(1);
  }
};

seedDatabase();
